### ISSUE TITLE
File Name 수정 문의 

### ISSUE THREAD

**Issue by changwookjun** [kakaobrain/KorNLUDatasets#1]
좋은 한국어 데이터 공개 감사드립니다. 

혹시 의도한 부분이 아니라면 아래 파일 확장자가 명확히 표현 되는건 어떤가요 ?

snli_1.0_train.kor ==>snli_1.0_train.kor.tsv

좋은 하루 되세요.

**Comment by hammouse** [comment]
`multinli.train.ko.tsv` 와 마찬가지로 `snli_1.0_train.ko.tsv` 로 변경하였습니다.

감사합니다.
